export enum MappingFieldEnums {
  IMPORTANT_PARAMS = "IMPORTANT_PARAMS",
  PRIMARY_KEYS = "PRIMARY_KEYS",
  DESTINATION_FIELDS = "DESTINATION_FIELDS",
  MISCELLANEOUS_FIELDS = "MISCELLANEOUS_FIELDS",
}
